<a href="https://colab.research.google.com/github/LucasLuckyxD/Portfolio-Project/blob/main/GamesData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Importing Libraries***

In [ ]:
import pandas as pd
import seaborn as sns

***Reading The Dataset***

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Dataset Pandas/Game Sales Data/dato.csv')
df

,Platform,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Rating,Critic_Score_Class
0,Wii,Sports,Nintendo,"41,36","28,96","3,77","8,45","82,54",E,Bueno
1,Wii,Racing,Nintendo,"15,68","12,8","3,79","3,29","35,57",E,Excelente
2,Wii,Sports,Nintendo,"15,61","10,95","3,28","2,95","32,78",E,Excelente
3,DS,Platform,Nintendo,"11,28","9,15","6,5","2,88","29,81",E,Excelente
4,Wii,Misc,Nintendo,"13,96","9,18","2,93","2,84","28,92",E,Malo
...,...,...,...,...,...,...,...,...,...,...
7107,PC,Action,Ubisoft,0,0,0,0,"0,01",T,Excelente
7108,PC,Shooter,Midway Games,0,0,0,0,"0,01",T,Aceptable
7109,PC,Sports,Sega,0,0,0,0,"0,01",E,Aceptable
7110,PC,Strategy,Take-Two Interactive,0,0,0,0,"0,01",E10+,Aceptable
7111,PS4,Platform,Team Meat,0,0,0,0,"0,01",T,Excelente

***Replacing the ',' into '.' for mathematical Calculation***

In [ ]:
df.dtypes

Platform              object
Genre                 object
Publisher             object
NA_Sales              object
EU_Sales              object
JP_Sales              object
Other_Sales           object
Global_Sales          object
Rating                object
Critic_Score_Class    object
dtype: object

In [ ]:
df= df.applymap(lambda x:x.replace(',','.'))

In [ ]:
df

,Platform,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Rating,Critic_Score_Class
0,Wii,Sports,Nintendo,41.36,28.96,3.77,8.45,82.54,E,Bueno
1,Wii,Racing,Nintendo,15.68,12.8,3.79,3.29,35.57,E,Excelente
2,Wii,Sports,Nintendo,15.61,10.95,3.28,2.95,32.78,E,Excelente
3,DS,Platform,Nintendo,11.28,9.15,6.5,2.88,29.81,E,Excelente
4,Wii,Misc,Nintendo,13.96,9.18,2.93,2.84,28.92,E,Malo
...,...,...,...,...,...,...,...,...,...,...
7107,PC,Action,Ubisoft,0,0,0,0,0.01,T,Excelente
7108,PC,Shooter,Midway Games,0,0,0,0,0.01,T,Aceptable
7109,PC,Sports,Sega,0,0,0,0,0.01,E,Aceptable
7110,PC,Strategy,Take-Two Interactive,0,0,0,0,0.01,E10+,Aceptable
7111,PS4,Platform,Team Meat,0,0,0,0,0.01,T,Excelente

In [ ]:
df[['NA_Sales','EU_Sales','JP_Sales','Other_Sales','Global_Sales']] = df[['NA_Sales','EU_Sales','JP_Sales','Other_Sales','Global_Sales']].astype(float)

In [ ]:
df

,Platform,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Rating,Critic_Score_Class
0,Wii,Sports,Nintendo,41.36,28.96,3.77,8.45,82.54,E,Bueno
1,Wii,Racing,Nintendo,15.68,12.80,3.79,3.29,35.57,E,Excelente
2,Wii,Sports,Nintendo,15.61,10.95,3.28,2.95,32.78,E,Excelente
3,DS,Platform,Nintendo,11.28,9.15,6.50,2.88,29.81,E,Excelente
4,Wii,Misc,Nintendo,13.96,9.18,2.93,2.84,28.92,E,Malo
...,...,...,...,...,...,...,...,...,...,...
7107,PC,Action,Ubisoft,0.00,0.00,0.00,0.00,0.01,T,Excelente
7108,PC,Shooter,Midway Games,0.00,0.00,0.00,0.00,0.01,T,Aceptable
7109,PC,Sports,Sega,0.00,0.00,0.00,0.00,0.01,E,Aceptable
7110,PC,Strategy,Take-Two Interactive,0.00,0.00,0.00,0.00,0.01,E10+,Aceptable
7111,PS4,Platform,Team Meat,0.00,0.00,0.00,0.00,0.01,T,Excelente

***Ubisoft rating and Critic Score Class on PC with the Shooter Genre***

In [ ]:
group1 = df.groupby(['Publisher','Platform','Genre'])

In [ ]:
asdf = group1[['NA_Sales','EU_Sales','JP_Sales','Other_Sales','Global_Sales']].sum().reset_index()

In [ ]:
Ubisoft_Group = group1.get_group(('Ubisoft','PC','Shooter'))

In [ ]:
df_for_plot = pd.DataFrame()
df_for_plot = Ubisoft_Group.copy()
df_for_plot

,Platform,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Rating,Critic_Score_Class
1386,PC,Shooter,Ubisoft,0.22,0.63,0.0,0.12,0.96,M,Excelente
1983,PC,Shooter,Ubisoft,0.16,0.45,0.0,0.05,0.65,M,Excelente
2800,PC,Shooter,Ubisoft,0.23,0.16,0.0,0.04,0.43,M,Bueno
3859,PC,Shooter,Ubisoft,0.14,0.08,0.0,0.02,0.24,M,Bueno
4553,PC,Shooter,Ubisoft,0.05,0.10,0.0,0.02,0.17,M,Bueno
5216,PC,Shooter,Ubisoft,0.05,0.05,0.0,0.01,0.12,M,Malo
6305,PC,Shooter,Ubisoft,0.00,0.04,0.0,0.01,0.05,M,Excelente
6556,PC,Shooter,Ubisoft,0.00,0.03,0.0,0.00,0.03,M,Bueno
6724,PC,Shooter,Ubisoft,0.00,0.02,0.0,0.00,0.02,M,Bueno
6728,PC,Shooter,Ubisoft,0.00,0.02,0.0,0.00,0.02,M,Bueno
6918,PC,Shooter,Ubisoft,0.00,0.01,0.0,0.00,0.01,M,Bueno
7037,PC,Shooter,Ubisoft,0.00,0.01,0.0,0.00,0.01,T,Bueno